default_platform(:android)

platform :android do
  desc "Build and upload to Play Store internal track"
  lane :internal do
    gradle(
      task: "bundle",
      build_type: "Release",
      project_dir: "./"
    )
    upload_to_play_store(
      track: "internal",
      json_key: "fastlane/play_store_key.json",
      in_app_update_priority: 5
    )
  end
end
